services:
  zbx_custom:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zbx_custom
    ports:
      - 8000:8000
    networks:
      - zbx_custom

networks:
  zbx_custom:
    driver: bridge